### ISSUE TITLE
waiting for 10 empty blocks - how to disable

### ISSUE THREAD

**Issue by nk307** [drandreaskrueger/chainhammer#23] opened 2020-10-29 04:20 UTC
Hello there,
I am trying to setup quorum 7 nodes example using docker-compose and trying to use the chainhammer quorum scripts, whenever I am trying to start a listener, it says **connection refused**, is it because of using docker as a tool?
How do we use chainhammer scripts for quorum 7 nodes example setup using docker rather than vagrant?

**Comment by drandreaskrueger** [comment] 2020-10-30 13:37
You must first find out, how to actually connect to your node via RPC, before chainhammer can even begin to help you benchmarking it.

I have recently written a  new simplified testing script that will help you doing that, and [linked to it in the instructions](https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt): 

* download [test_RPC.py](https://github.com/drandreaskrueger/chainhammer/blob/master/hammer/test_RPC.py)
* `pip3 install requests`
* `python3 test_RPC.py` in terminal 1
* `geth --rpc --dev` in a new terminal 2
* press ENTER in terminal 1

That is the "example run", so that you can see how it will look when all is good.

Then kill `geth`, and instead start your own network, and rerun `test_RPC.py`.

If you have problems, please read the whole code. It's VERY simple code. And short. You [might have to change the RPC-address-and-port](https://github.com/drandreaskrueger/chainhammer/blob/35c965f504d2a4b98837c55b2b45d0c537c418ec/hammer/test_RPC.py#L18-L20).

Then when the script also runs through and shows "Yes, full success..." when NOT using the above geth example client, but YOUR network node, you're good to go.

**Comment by nk307** [comment] 2020-11-02 05:54
Thanks for the response.
I have changed the respective rpc address to my docker based ports for quorum node and test-RPC.py is giving success response. Now when I try to follow **[this](https://github.com/drandreaskrueger/chainhammer/blob/master/results/quorum.md)**, 
Steps.
Starting listener tps.py
Blocking send.py 1000

The output of the two screens is as follows:
tps.py
**web3 connection established, blockNumber = 113, node version string =  Geth/node1-raft/v1.9.7-stable-9339be03(quorum-v2.6.0)/linux-amd64/go1.13.10
first account of node is 0xed9d02e382b34818e88B88a309c7fe71E65f419d, balance is 1000000000 Ether
WARN: raft consensus did report timestamps in nanoseconds. Is that still the case?
nodeName: Quorum, nodeType: Geth, nodeVersion: node1-raft, consensus: raft, network: 10, chainName: ???, chainId: -1

Block  113  - waiting for something to happen
(filedate 1603860512) last contract address: 0xc305c901078781C232A2a521C2aF7980f8385ee9**


Send.py
**blocknumber now: 225 waiting for 10 empty blocks:**

Am I missing something, why is it getting hung up here?

**Comment by drandreaskrueger** [comment] 2020-11-02 12:11
> I have changed the respective rpc address to my docker based ports for quorum node  
> and test-RPC.py is giving success response.

First of all: Great. Well done.

Which RPCaddress have you changed it to, for your "7 nodes example"?  
That might also help @Mohammed-alzuharey in his issues there https://github.com/drandreaskrueger/chainhammer/issues/22#issuecomment-716510271 and https://github.com/drandreaskrueger/chainhammer/issues/21#issuecomment-708015235

---

> Now when I try to follow this,  

Those are actually very old instructions. Not sure whether they still work. No time to try.

Have a look at these much newer ones:  https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt

---

> Block 113 - waiting for something to happen  

Now great, so the first >100 blocks were actually filled?  That is very good news, right?

---

> why is it getting hung up here?

At the end of send.py in many cases it "waits for 10 empty blocks", see this code here:

https://github.com/drandreaskrueger/chainhammer/blob/e999a7d3c9209447fca6b80a8665458d94fb8edd/hammer/send.py#L553-L593
called here
https://github.com/drandreaskrueger/chainhammer/blob/e999a7d3c9209447fca6b80a8665458d94fb8edd/hammer/send.py#L693

!! --> I had to make a lot of  exceptions though, because every fricking Ethereum implementation is somehow different; it's tough to code on top of a system with such few (or differing) standards:   
https://github.com/drandreaskrueger/chainhammer/blob/e999a7d3c9209447fca6b80a8665458d94fb8edd/hammer/send.py#L581
Now this ^ will help you.

Your system is reported like this:  
> nodeName: Quorum, nodeType: Geth, nodeVersion: node1-raft, consensus: raft, network: 10, chainName: ???, chainId: -1

so you could add to that condition

    ... or NODENAME=="Quorum":

then it would skip those 10 blocks waiting completely.

---

Hmmm ... A TODO for me for future code could be to read an environment variable that you could set in the bash CLI:

    WAIT_A_FEW_BLOCKS_AT_THE_END=false

and that then would allow anyone to _always skip_ that routine `wait_some_blocks()` without having to change the code itself.

But the above suggestion does the same for you. Just edit the python code as described.

---

I suggest you keep terminals open for all the log files

```
tail -f logs/send.py.log
tail -f logs/deploy.py.log
tail -f logs/network.log
tail -f logs/tps.py.log
```
that helps to spot errors when they appear.

---

Good luck!

**Comment by drandreaskrueger** [comment] 2020-11-02 12:18
I have changed the name of the topic so others can benefit from this.

Please open a new issue if you have new problems. Thanks.

**Comment by nk307** [comment] 2020-11-02 12:22
Thanks for the response,
I have changed the RPCAddress in config.py port to 22000 after attaching the geth to the desired node(in my case (node-1), and it is able to connect to a docker based 7 nodes examples. 

I will try changing the code as described and will update if any improvements.

**Comment by drandreaskrueger** [comment] 2020-11-02 12:30
Great, thanks.

Alternatively, just set this to zero:

https://github.com/drandreaskrueger/chainhammer/blob/35f1a96a791d9e75e46f22f03af1dca079b42305/hammer/config.py#L108-L109

    EMPTY_BLOCKS_AT_END = 0

**Comment by nk307** [comment] 2020-11-02 12:34
Thanks for the update, configured it in config.py as well.
Tried with it, now send.py is able to exit, but when I look at listener (tps.py),
I can only see:

Block  148  - waiting for something to happen
(filedate 1603860512) last contract address: 0xc305c901078781C232A2a521C2aF7980f8385ee9,
Is there any other modification required?

**Comment by drandreaskrueger** [comment] 2020-11-02 12:36
Plus I suggest to also read this issue https://github.com/drandreaskrueger/chainhammer/issues/20 in case some of your possible problems are already solved there

**Comment by drandreaskrueger** [comment] 2020-11-02 12:38
Are there blocks produced and filled at all?

Please delete all logs/* files, rerun, and then cite all the new logs/* here.

**Comment by drandreaskrueger** [comment] 2020-11-02 12:39
When you follow https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt what is the output of send.py ?

**Comment by drandreaskrueger** [comment] 2020-11-02 12:41
open a new issue for that please

**Comment by nk307** [comment] 2020-11-02 12:44
> Are there blocks produced and filled at all?

I think there is some issue here, when I delete all logs and rerun, it throws no files remaining, why are logs not being generated?

**Comment by nk307** [comment] 2020-11-02 12:46
> When you follow https://github.com/drandreaskrueger/chainhammer/blob/master/docs/azure.md#cloud-connection-attempt what is the full output of deploy.py and send.py ?

Will try this and open a new issue but before that, can we find out where is the problem in terms of tps.py, why is it not able to interact?

**Comment by drandreaskrueger** [comment] 2020-11-02 12:53
Oh sorry, yes the log files are generated when you start run.sh or run-all_small.sh but don't do that just yet, you must first understand all the separate steps. I suggest you read https://github.com/drandreaskrueger/chainhammer/blob/master/run.sh to see how the different parts are started and generate log files.

What I meant was: please report full outputs of the different scripts. Just citing some lines of the output will not make me understand your situation.

---

tps.py does work, otherwise it would not show the blocknumber:

> (tps.py), I can only see:  
> Block 148 - waiting for something to happen

so the problem is either with send.py or deploy.py

---

Closing this issue, because your issues were first the wrong RPCaddress, and then the waiting 10 blocks at the end, and both are solved now.

**Closed by drandreaskrueger** 2020-11-02 12:53 UTC
